name: Run Makefile Command

on: push
        
jobs:
    tests:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            
          - name: Run make Command
            run: make say-hello